name: provisioning ecr-eb

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  MODULE_NAME: ${{ vars.MODULE_NAME }}
  S3_BUCKET: ${{ vars.BUCKET_S3 }}

jobs:
  provisioning:
    runs-on: ubuntu-latest
    env:
      TF_VAR_AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      TF_VAR_MODULE_NAME: ${{ vars.MODULE_NAME }}
      TF_VAR_S3_BUCKET: ${{ vars.BUCKET_S3 }}
      TF_VAR_SOLUTION_STACK_NAME: ${{ vars.STACK_NAME }}
      TF_VAR_WORKING_DIR: ".environment"
      TF_VAR_PLAN_FILE: "planfile"
      TF_VAR_STATE_FILE: "state/terraform.tfstate"

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR init \
            -backend-config="bucket=$TF_VAR_S3_BUCKET" \
            -backend-config="key=$TF_VAR_STATE_FILE"

      - name: Terraform Import (if not in state)
        run: |
          set -e
          cd $TF_VAR_WORKING_DIR

          # ECR
          if ! terraform state show aws_ecr_repository.cyo_ecr_repo > /dev/null 2>&1; then
            terraform import aws_ecr_repository.cyo_ecr_repo "${PROJECT_NAME}/${MODULE_NAME}"
          fi

          # Elastic Beanstalk Application
          if ! terraform state show aws_elastic_beanstalk_application.cyo_eba > /dev/null 2>&1; then
            terraform import aws_elastic_beanstalk_application.cyo_eba "${PROJECT_NAME}"
          fi

          # Elastic Beanstalk Environment
          if ! terraform state show aws_elastic_beanstalk_environment.cyo_ebef > /dev/null 2>&1; then
            terraform import aws_elastic_beanstalk_environment.cyo_ebef "e-h3q33aqsij"
          fi

      - name: Terraform Plan
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR plan \
            -input=false -out=$TF_VAR_PLAN_FILE

      - name: Terraform Apply
        run: |
          terraform -chdir=$TF_VAR_WORKING_DIR apply \
            -auto-approve $TF_VAR_PLAN_FILE
